import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseSchema } from "../schema.ts";
import { enabledExtensionIds, type ParsedExtensionsConfig } from "./config.ts";
import { ExtensionGuestModulePathSchema, ROOTCELL_EXTENSIONS, type ExtensionGuestHook } from "./registry.ts";

export const GENERATED_EXTENSION_HOOK_FILES = [
  "extensions-agent-vm.nix",
  "extensions-firewall-vm.nix",
  "extensions-home-manager.nix",
] as const;

const HOOK_FILE_NAMES: Readonly<Record<ExtensionGuestHook, (typeof GENERATED_EXTENSION_HOOK_FILES)[number]>> = {
  agentNixos: "extensions-agent-vm.nix",
  firewallNixos: "extensions-firewall-vm.nix",
  homeManager: "extensions-home-manager.nix",
};

export function writeExtensionNixAggregators(
  generatedDir: string,
  config: ParsedExtensionsConfig,
): void {
  for (const hook of ["agentNixos", "firewallNixos", "homeManager"] as const) {
    writeFileSync(
      join(generatedDir, HOOK_FILE_NAMES[hook]),
      renderExtensionNixAggregator(config, hook),
      "utf8",
    );
  }
}

export function renderExtensionNixAggregator(
  config: ParsedExtensionsConfig,
  hook: ExtensionGuestHook,
): string {
  const imports = enabledExtensionIds(config).flatMap((id) => {
    const definition = ROOTCELL_EXTENSIONS.find((extension) => extension.id === id);
    return definition?.guestHooks[hook] ?? [];
  });
  return [
    "# Generated by ./rootcell from this instance's extensions.txt. DO NOT EDIT.",
    "{ ... }:",
    "{",
    "  imports = [",
    ...imports.map((path) => `    ../${nixPath(path)}`),
    "  ];",
    "}",
    "",
  ].join("\n");
}

function nixPath(path: string): string {
  return parseSchema(ExtensionGuestModulePathSchema, path, "unsafe extension Nix import path");
}
