{ config, pkgs, lib, ... }:

# Firewall VM: a tiny appliance VM that brokers all egress for the agent VM.
#
# Two NICs:
#   enp0s1  vzNAT       — internet egress (default route)
#   lima0   lima:host   — private link to the agent VM (192.168.106.0/24)
#
# Two services:
#   mitmproxy :8080  — HTTP CONNECT proxy in TLS-passthrough mode. Reads
#                      SNI from the ClientHello; allow/deny against
#                      /etc/agent-vm/allowed-https.txt. SSH-via-CONNECT
#                      uses /etc/agent-vm/allowed-ssh.txt.
#   dnsmasq   :53    — Names matching /etc/agent-vm/allowed-dns.txt are
#                      forwarded to 1.1.1.1; everything else returns
#                      0.0.0.0 (effective NXDOMAIN).
#
# Allowlists are mutable runtime files (NOT Nix-store) so `./agent allow`
# can hot-reload them without a guest rebuild.

{
  imports = [ ./common.nix ];

  networking.hostName = "firewall-vm";

  # ── Networking ────────────────────────────────────────────────────────
  networking.useDHCP = false;
  networking.useNetworkd = true;
  systemd.network.enable = true;

  # enp0s1 = vzNAT, our internet-egress NIC. Default route lives here.
  systemd.network.networks."10-enp0s1" = {
    matchConfig.Name = "enp0s1";
    networkConfig.DHCP = "ipv4";
  };

  # lima0 = lima:host, our private link to the agent VM. Static address;
  # DHCP would conflict with the agent's static .2.
  systemd.network.networks."20-lima0" = {
    matchConfig.Name = "lima0";
    networkConfig = {
      DHCP = "no";
      IPv6AcceptRA = false;
      LinkLocalAddressing = "no";
    };
    address = [ "192.168.106.1/24" ];
  };

  boot.kernel.sysctl = {
    # We are the proxy, not a NAT gateway. Don't forward packets between
    # the inter-VM link and the internet at the IP layer — force everything
    # through mitmproxy/dnsmasq at the application layer.
    "net.ipv4.ip_forward" = 0;
    "net.ipv6.conf.all.forwarding" = 0;
    # No v6 anywhere; simpler threat model.
    "net.ipv6.conf.all.disable_ipv6" = 1;
    "net.ipv6.conf.default.disable_ipv6" = 1;
  };

  # ── Firewall ──────────────────────────────────────────────────────────
  # Only :8080 (mitmproxy) and :53 (dnsmasq) are reachable from the agent
  # VM. SSH on enp0s1 is left to lima/openssh defaults — host-only.
  networking.firewall = {
    enable = true;
    interfaces.lima0 = {
      allowedTCPPorts = [ 8080 ];
      allowedUDPPorts = [ 53 ];
    };
  };

  # ── Mutable allowlist directory ───────────────────────────────────────
  # `./agent allow` writes here via `limactl cp`. Not in the Nix store.
  systemd.tmpfiles.rules = [
    "d /etc/agent-vm 0755 root root -"
  ];

  # ── mitmproxy service ─────────────────────────────────────────────────
  # The addon is in /etc via environment.etc so it has a stable path that
  # systemd's strict sandboxing can read. The addon stats the allowlist
  # files on every TLS ClientHello and reloads on mtime change, so edits
  # via `./agent allow` take effect with no service restart.
  environment.etc."agent-vm/mitmproxy_addon.py".source = ./proxy/mitmproxy_addon.py;

  systemd.services.mitmproxy = {
    description = "mitmproxy SNI-allowlist firewall";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      ExecStart = lib.concatStringsSep " " [
        "${pkgs.mitmproxy}/bin/mitmdump"
        "--mode regular"
        "--listen-host 192.168.106.1"
        "--listen-port 8080"
        "--set termlog_verbosity=warn"
        "--set flow_detail=0"
        "-s /etc/agent-vm/mitmproxy_addon.py"
      ];
      DynamicUser = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      NoNewPrivileges = true;
      ReadOnlyPaths = "/etc/agent-vm";
      Restart = "on-failure";
      RestartSec = "2s";
    };
  };

  # ── dnsmasq service ───────────────────────────────────────────────────
  # The conf-file is generated by /etc/agent-vm/reload.sh from
  # allowed-dns.txt and reloaded with SIGHUP. On first boot the file
  # may not exist yet — services.dnsmasq tolerates that.
  services.dnsmasq = {
    enable = true;
    resolveLocalQueries = false;
    settings = {
      listen-address = "192.168.106.1";
      bind-interfaces = true;
      no-resolv = true;
      domain-needed = true;
      bogus-priv = true;
      conf-file = "/etc/agent-vm/dnsmasq-allowlist.conf";
    };
  };

  # ── Reload helper ─────────────────────────────────────────────────────
  # `./agent allow` runs this after copying new allowlist files in.
  environment.etc."agent-vm/reload.sh" = {
    source = ./proxy/reload.sh;
    mode = "0755";
  };
}
