{ config, pkgs, lib, username, ... }:

# All user-level tooling lives here. Iterate with `home-manager switch`,
# which is fast and doesn't touch the system closure.
#
# Pi reads provider keys from the env. DON'T put them in this file — the
# Nix store is world-readable. Configure secret entries in secrets.env; `rootcell`
# reads those provider-backed secrets on the host and exports them on guest
# sessions.

let
  net = import ./network.nix;
  pi-coding-agent = import ./pi/pi-coding-agent.nix { inherit pkgs; };
in
{
  # Per-user git identity, generated by `rootcell` from the host's `git config`.
  # Absent on a clean checkout — the mkDefault values below apply in that case.
  imports =
    lib.optional (builtins.pathExists ./git-local.nix) ./git-local.nix
    ++ lib.optional (builtins.pathExists ./generated/extensions-home-manager.nix)
      ./generated/extensions-home-manager.nix;

  home.username = username;
  home.homeDirectory = "/home/${username}";
  home.stateVersion = "26.05";

  home.packages = with pkgs; [
    # The reason this VM exists.
    pi-coding-agent

    # Pi shells out to these.
    ripgrep
    fd

    # Core dev CLIs
    gh              # GitHub CLI; agents use this a lot
    curl
    wget
    rsync
    jq
    yq-go
    tree
    htop
    tmux
    unzip
    zstd
    gnupg
    dnsutils        # dig, nslookup
    iputils         # ping
    netcat-openbsd

    # Build toolchain (build-essential equivalent)
    gcc
    gnumake
    pkg-config

    # Editor
    neovim
  ];

  # Pi discovers skills under ~/.pi/agent/skills/<name>/SKILL.md (progressive
  # disclosure: only the front-matter description goes in the system prompt;
  # pi loads the full body when a task matches). Per-project AGENTS.md /
  # CLAUDE.md and .pi/skills/ are picked up separately by walking up from
  # the cwd.
  #
  # `recursive = true` is load-bearing: with it, home-manager's home-files
  # derivation uses `lndir` to build a real directory tree containing one
  # symlink per leaf file, so ~/.pi/agent/skills/ stays a real directory
  # (the user can add their own skills alongside) AND each managed skill's
  # interior is per-file symlinks (so editing SKILL.md and re-provisioning
  # only swaps the SKILL.md symlink target). With the default
  # `recursive = false`, home-manager symlinks the whole skill directory
  # to a nix-store path; the next `home-manager switch` then can't replace
  # it cleanly when content changes — `cmp` errors on directory targets
  # and `mv` fails because the nix-store parent is read-only — leaving
  # activation in a half-broken state.
  home.file.".pi/agent/skills/add-flake-dep" = {
    source = ./pi/agent/skills/add-flake-dep;
    recursive = true;
  };
  home.file.".pi/agent/skills/network-allowlist" = {
    source = ./pi/agent/skills/network-allowlist;
    recursive = true;
  };

  programs.bash = {
    enable = true;
    enableCompletion = true;
    shellAliases = {
      vi = "nvim";
      vim = "nvim";
    };
  };

  # direnv + nix-direnv: drop a flake.nix in any project dir and have its
  # toolchain auto-load. Per-project tooling (Node, Python, Rust, etc.)
  # belongs there, not in this file.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # git-delta as the git pager. The `enableGitIntegration` flag writes the
  # `[core] pager = delta` and `[interactive] diffFilter = delta` entries
  # into git's config.
  programs.delta = {
    enable = true;
    enableGitIntegration = true;
  };

  # `programs.git.enable` adds git itself, so we don't list it above.
  programs.git = {
    enable = true;
    settings = {
      user.name  = lib.mkDefault "agent";
      user.email = lib.mkDefault "agent@localhost";
      init.defaultBranch = "main";
      pull.rebase = true;
      push.default = "current";
      push.autoSetupRemote = true;
    };
  };

  # All SSH egress tunnels through the firewall VM via HTTP CONNECT, where
  # mitmproxy applies the allowed-ssh.txt allowlist. No exceptions —
  # attempts to SSH back to the host fall through this rule too and get denied
  # unless explicitly allowlisted. Rootcell's host→guest management SSH is a
  # separate inbound path and this client config does not touch it.
  programs.ssh = {
    enable = true;
    # Don't pull in home-manager's default ProxyCommand/ServerAlive/etc;
    # we only want our own settings. Silences the deprecation warning
    # asking us to opt into the new explicit-defaults behavior.
    enableDefaultConfig = false;

    settings = {
      "*" = {
        ProxyCommand = "${pkgs.netcat-openbsd}/bin/nc -X connect -x ${net.firewallIp}:8080 %h %p";
      };

      "ssh.dev.azure.com" = {
        # Disable weak crypto warnings - Azure Devops does not support post-quantum yet
        WarnWeakCrypto = "no-pq-kex";
      };

      "bitbucket.org" = {
        WarnWeakCrypto = "no-pq-kex";
      };
    };

    # Look in our seeded read-only file in addition to the user-writable
    # default so first-run `git clone` doesn't prompt for known hosts.
    # home-manager's `programs.ssh.knownHosts` doesn't exist (that's a
    # NixOS-only option); we seed manually via home.file below.
    extraConfig = ''
      UserKnownHostsFile ~/.ssh/known_hosts ~/.ssh/known_hosts.d/seeded
    '';
  };

  # Generate a per-VM SSH key on first provision so `git push git@github.com:...`
  # works from inside the VM. RSA-4096 (not ed25519) because Azure DevOps still
  # rejects ed25519 keys. Idempotent — guarded on file absence, so re-running
  # `home-manager switch` never replaces an existing key. The private key stays
  # inside the VM; only the .pub is meant to leave (via `./rootcell pubkey`).
  home.activation.generateAgentVmSshKey = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if [ ! -f "$HOME/.ssh/id_rsa" ]; then
      mkdir -p "$HOME/.ssh"
      chmod 0700 "$HOME/.ssh"
      ${pkgs.openssh}/bin/ssh-keygen -t rsa -b 4096 -N "" \
        -C "agent-vm" \
        -f "$HOME/.ssh/id_rsa"
    fi
  '';

  # Pre-seeded SSH host keys for hosts in proxy/allowed-ssh.txt. Update by
  # running `ssh-keyscan -t ed25519 <host>` (or `-t rsa` for ssh.dev.azure.com).
  home.file.".ssh/known_hosts.d/seeded".text = ''
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
    bitbucket.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO
    ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
  '';
}
