{ config, pkgs, lib, username, ... }:

# All user-level tooling lives here. Iterate with `home-manager switch`,
# which is fast and doesn't touch the system closure.
#
# Pi reads its provider key from the env. DON'T put it in this file — the
# Nix store is world-readable. Export it from your shell each session, or
# stash it in a non-tracked file inside the VM (the `agent` script reads
# it from macOS Keychain on the host and exports it on `limactl shell`).

let
  # Pi (pi.dev) ships a Bun-compiled standalone binary on each release, so
  # we don't need Node.js in the VM at all. Pinned by version + sha256 —
  # bump both fields together. Latest at:
  #   https://github.com/badlogic/pi-mono/releases
  #
  # The release tarball contains the binary plus runtime resources it
  # reads at startup (themes, export-html template, a wasm blob, and
  # package.json for the version string). Copy the whole unpacked tree
  # under $out/share so we don't have to track which files are needed,
  # and symlink the binary into $out/bin so `pi` is on PATH.
  pi-coding-agent = pkgs.stdenv.mkDerivation rec {
    pname = "pi-coding-agent";
    version = "0.74.0";

    src = pkgs.fetchurl {
      url = "https://github.com/badlogic/pi-mono/releases/download/v${version}/pi-linux-arm64.tar.gz";
      sha256 = "261aa912878ca983c903d9c4a0408310dd8637b583085651d9b5ddb70c9df572";
    };

    # Patch the bundled ELF interpreter to point at glibc inside the Nix
    # store; otherwise the binary fails immediately on NixOS, which has no
    # /lib64/ld-linux-aarch64.so.1.
    nativeBuildInputs = [ pkgs.autoPatchelfHook ];
    buildInputs = [ pkgs.stdenv.cc.cc.lib ];

    installPhase = ''
      runHook preInstall
      mkdir -p $out/share/pi-coding-agent $out/bin
      cp -r . $out/share/pi-coding-agent/
      ln -s $out/share/pi-coding-agent/pi $out/bin/pi
      runHook postInstall
    '';

    # Bun-compiled binaries embed a custom section that strip(1) corrupts.
    dontStrip = true;
  };
in
{
  # Per-user git identity, generated by `agent` from the host's `git config`.
  # Absent on a clean checkout — the mkDefault values below apply in that case.
  imports = lib.optional (builtins.pathExists ./git-local.nix) ./git-local.nix;

  home.username = username;
  home.homeDirectory = "/home/${username}";
  home.stateVersion = "25.11";

  home.packages = with pkgs; [
    # The reason this VM exists.
    pi-coding-agent

    # Pi shells out to these.
    ripgrep
    fd

    # Core dev CLIs
    gh              # GitHub CLI; agents use this a lot
    curl
    wget
    rsync
    jq
    yq-go
    tree
    htop
    tmux
    unzip
    zstd
    gnupg
    dnsutils        # dig, nslookup
    iputils         # ping
    netcat-openbsd

    # Build toolchain (build-essential equivalent)
    gcc
    gnumake
    pkg-config

    # Editor
    neovim
  ];

  # Pi auto-loads ~/.pi/agent/AGENTS.md as global instructions and discovers
  # skills under ~/.pi/agent/skills/<name>/SKILL.md (progressive disclosure:
  # only the front-matter description goes in the system prompt; pi loads
  # the full body when a task matches). Per-project AGENTS.md/CLAUDE.md and
  # .pi/skills/ are picked up separately by walking up from the cwd.
  home.file.".pi/agent/AGENTS.md".source = ./pi/agent/AGENTS.md;
  home.file.".pi/agent/skills".source = ./pi/agent/skills;

  programs.bash = {
    enable = true;
    enableCompletion = true;
    shellAliases = {
      vi = "nvim";
      vim = "nvim";
    };
  };

  # direnv + nix-direnv: drop a flake.nix in any project dir and have its
  # toolchain auto-load. Per-project tooling (Node, Python, Rust, etc.)
  # belongs there, not in this file.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  # git-delta as the git pager. The `enableGitIntegration` flag writes the
  # `[core] pager = delta` and `[interactive] diffFilter = delta` entries
  # into git's config.
  programs.delta = {
    enable = true;
    enableGitIntegration = true;
  };

  # `programs.git.enable` adds git itself, so we don't list it above.
  programs.git = {
    enable = true;
    settings = {
      user.name  = lib.mkDefault "agent";
      user.email = lib.mkDefault "agent@localhost";
      init.defaultBranch = "main";
      pull.rebase = true;
    };
  };

  # All SSH egress tunnels through the firewall VM via HTTP CONNECT, where
  # mitmproxy applies the allowed-ssh.txt allowlist. No exceptions —
  # `ssh host.lima.internal` falls through this rule too and gets denied
  # by the firewall (host.lima.internal isn't on the SSH allowlist), so
  # the VM has no path to SSH back to the host. (limactl shell / cp use
  # Lima's own host→guest vsock transport on the *server* side, which
  # this client config doesn't touch.)
  programs.ssh = {
    enable = true;
    matchBlocks."*".proxyCommand =
      "${pkgs.netcat-openbsd}/bin/nc -X connect -x 192.168.106.1:8080 %h %p";
    # Pre-seed known_hosts so first-run `git clone` doesn't prompt. Update
    # by running `ssh-keyscan github.com` etc. on a trusted host.
    knownHosts = {
      github = {
        hostNames = [ "github.com" ];
        publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl";
      };
      gitlab = {
        hostNames = [ "gitlab.com" ];
        publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf";
      };
      bitbucket = {
        hostNames = [ "bitbucket.org" ];
        publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIazEu89wgQZ4bqs3d63QSMzYVa0MuJ2e2gKTKqu+UUO";
      };
      azure-devops = {
        # ssh.dev.azure.com only publishes an RSA host key (no ed25519).
        hostNames = [ "ssh.dev.azure.com" ];
        publicKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H";
      };
    };
  };
}
